package finalprojectpbo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Admin extends javax.swing.JFrame {
    
    String sql;
    static Connection con;
    static Statement stm;
    static ResultSet rs;
    
    String kodekapal;
    String namakapal;
    String bebanmaks;
    String namakapten;
    String asal;
    String tujuan;
    String keberangkatan;
    String kedatangan;
    String container;
    String bebanbarang;
    
    public void tampil_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Kapal");
        model.addColumn("Nama Kapal");
        model.addColumn("Beban Maks (kg)");
        model.addColumn("Nama Kapten");
        model.addColumn("Asal");
        model.addColumn("Tujuan");
        model.addColumn("Keberangkatan");
        model.addColumn("Kedatangan");
        model.addColumn("Container");
        model.addColumn("Beban Bawaan (kg)");
        
        try{
            sql ="SELECT * FROM kapal";
            con = (Connection) config.configDB();
            stm = con.createStatement();
            rs  = stm.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), 
                                          rs.getString(3), rs.getString(4), 
                                          rs.getString(5), rs.getString(6), 
                                          rs.getString(7), rs.getString(8),
                                          rs.getString(9), rs.getString(10)});
            }
            tabelKapal.setModel(model);

        }catch(SQLException e){
            System.out.println("Error = "+e.getMessage());
        }
    }
    
    private void cari_dan_hapus(){
        String hapus = JOptionPane.showInputDialog("Masukkan Kode Kapal : ");
        if (hapus.isEmpty()){
            JOptionPane.showMessageDialog(this, "Kode Kapal belum diinputkan, Hapus data Dibatalkan!");
        }else{
            try{
            sql = "SELECT * FROM kapal WHERE kode_kapal = '"+hapus+"'";
            
                con = (Connection) config.configDB();
                stm = con.createStatement();
                rs = stm.executeQuery(sql);
            
                while(rs.next()){
                    kodekapal       = rs.getString(1);
                    namakapal       = rs.getString(2);
                    bebanmaks       = rs.getString(3);
                    namakapten      = rs.getString(4);
                    asal            = rs.getString(5);
                    tujuan          = rs.getString(6);
                    keberangkatan   = rs.getString(7);
                    kedatangan      = rs.getString(8);
                    container       = rs.getString(9);
                    bebanbarang     = rs.getString(10);
                }
                int response = JOptionPane.showConfirmDialog(null,"Data yang ingin Dihapus : \nKode Kapal : "+kodekapal +"\nNama Kapal :"+namakapal 
                        +"\nBeban Maks = "+bebanmaks +"\nNama Kapten:"+namakapten 
                        +"\nAsal : "+asal +"\nTujuan : "+tujuan +"\nKeberangkatan : "+keberangkatan 
                        +"\nKedatangan : "+kedatangan +"\nContainer : "+container + "\nBeban Barang :"
                        +bebanbarang +"\nApakah Anda ingin Menghapus data Ini?","Hapus",
                        JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if(response == JOptionPane.YES_OPTION){
                    sql = "DELETE FROM kapal WHERE kode_kapal = '"+hapus+"'";
                    con = (Connection) config.configDB();
                    stm = con.createStatement();
                    stm.executeUpdate(sql);
                    JOptionPane.showMessageDialog(this,"Data Berhasil Terhapus");
                    tampil_data();
                }else{
                    JOptionPane.showMessageDialog(this,"Penghapusan data dibatalkan!!");
                }
            }catch(SQLException e){
                System.out.println("Error = "+e.getMessage());
            }
        }
    }

    public Admin() {
        initComponents();
        tampil_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKapal = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tbTambah = new javax.swing.JButton();
        tbEdit = new javax.swing.JButton();
        tbHapus = new javax.swing.JButton();
        tbRefresh = new javax.swing.JButton();
        tbLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelKapal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKapal.setEnabled(false);
        jScrollPane1.setViewportView(tabelKapal);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Data Kapal");

        tbTambah.setBackground(new java.awt.Color(0, 255, 0));
        tbTambah.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbTambah.setForeground(new java.awt.Color(0, 0, 0));
        tbTambah.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\finalprojectpbo\\src\\resource\\add.png")); // NOI18N
        tbTambah.setText("Tambah");
        tbTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbTambah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTambahActionPerformed(evt);
            }
        });

        tbEdit.setBackground(new java.awt.Color(255, 255, 102));
        tbEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbEdit.setForeground(new java.awt.Color(0, 0, 0));
        tbEdit.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\finalprojectpbo\\src\\resource\\edit.png")); // NOI18N
        tbEdit.setText("Edit");
        tbEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEditActionPerformed(evt);
            }
        });

        tbHapus.setBackground(new java.awt.Color(204, 0, 0));
        tbHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbHapus.setForeground(new java.awt.Color(0, 0, 0));
        tbHapus.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\finalprojectpbo\\src\\resource\\hapus.png")); // NOI18N
        tbHapus.setText("Hapus");
        tbHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbHapus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapusActionPerformed(evt);
            }
        });

        tbRefresh.setBackground(new java.awt.Color(0, 204, 204));
        tbRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbRefresh.setForeground(new java.awt.Color(0, 0, 0));
        tbRefresh.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\finalprojectpbo\\src\\resource\\refresh.png")); // NOI18N
        tbRefresh.setText("Refresh");
        tbRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbRefreshActionPerformed(evt);
            }
        });

        tbLogout.setText("Logout");
        tbLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1190, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbHapus)
                .addGap(501, 501, 501))
            .addGroup(layout.createSequentialGroup()
                .addGap(519, 519, 519)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbLogout)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tbLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbTambah)
                    .addComponent(tbEdit)
                    .addComponent(tbHapus)
                    .addComponent(tbRefresh))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTambahActionPerformed
        tambahdata td = new tambahdata();
        td.setVisible(true);
    }//GEN-LAST:event_tbTambahActionPerformed

    private void tbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapusActionPerformed
        cari_dan_hapus();
    }//GEN-LAST:event_tbHapusActionPerformed

    private void tbRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbRefreshActionPerformed
        tampil_data();
    }//GEN-LAST:event_tbRefreshActionPerformed

    private void tbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEditActionPerformed
       editdata ed = new editdata();
       ed.setVisible(true);
    }//GEN-LAST:event_tbEditActionPerformed

    private void tbLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbLogoutActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Apakah anda Ingin Logout??","Logout"
                ,JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
            landingpage lp = new landingpage();
            lp.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_tbLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKapal;
    private javax.swing.JButton tbEdit;
    private javax.swing.JButton tbHapus;
    private javax.swing.JButton tbLogout;
    private javax.swing.JButton tbRefresh;
    private javax.swing.JButton tbTambah;
    // End of variables declaration//GEN-END:variables
}
