package finalprojectpbo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class editdata extends javax.swing.JFrame {
    String sql;
    static Connection con;
    static Statement stm;
    static ResultSet rs;
    
    String kodekapal;
    String namakapal;
    int bebanmaks;
    String namakapten;
    String asal;
    String tujuan;
    String keberangkatan;
    String kedatangan;
    String container;
    int bebanbarang;
    private void get_text(){
        kodekapal = txtKodeKapal.getText();
        namakapal = txtNamaKapal.getText();
        bebanmaks = Integer.parseInt(txtBebanMaks.getText());
        namakapten = txtNamaKapten.getText();
        asal = txtAsal.getText();
        tujuan = txtTujuan.getText();
        keberangkatan = txtKeberangkatan.getText();
        kedatangan = txtKedatangan.getText();
        container = txtContainer.getText();
        bebanbarang = Integer.parseInt(txtBebanBarang.getText());
    }
    private void cari(){
        String cari = txtCariKodeKapal.getText();
        if(cari.isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Masukkan Kode Kapal Terlebih dahulu!!");
            clear();
        }else{
            try{
                sql = "SELECT * FROM kapal WHERE kode_kapal='"+cari+"'";
                con = (Connection) config.configDB();
                stm = con.createStatement();
                rs = stm.executeQuery(sql);
            
                while(rs.next()){
                    kodekapal       = rs.getString(1);
                    namakapal       = rs.getString(2);
                    bebanmaks       = Integer.parseInt(rs.getString(3));
                    namakapten      = rs.getString(4);
                    asal            = rs.getString(5);
                    tujuan          = rs.getString(6);
                    keberangkatan   = rs.getString(7);
                    kedatangan      = rs.getString(8);
                    container       = rs.getString(9);
                    bebanbarang     = Integer.parseInt(rs.getString(10));
                }
                if(kodekapal.equals("")){
                    JOptionPane.showMessageDialog(this,"Kode Kapal yang anda masukkan tidak ada dalam database");
                    txtCariKodeKapal.setText(null);
                }else{
                    txtKodeKapal.setText(kodekapal);
                    txtNamaKapal.setText(namakapal);
                    txtBebanMaks.setText(String.valueOf(bebanmaks));
                    txtNamaKapten.setText(namakapten);
                    txtAsal.setText(asal);
                    txtTujuan.setText(tujuan);
                    txtKeberangkatan.setText(keberangkatan);
                    txtKedatangan.setText(kedatangan);
                    txtContainer.setText(container);
                    txtBebanBarang.setText(String.valueOf(bebanbarang));
                }
            }catch(SQLException e){
                System.out.println("Error = "+e.getMessage());
            }
        }
    }
    
    private void edit_data(){
        get_text();
        try{
        sql = "UPDATE kapal SET kode_kapal = '" +kodekapal+ "', nama_kapal = '" 
                +namakapal+ "', Container_MAX = '" +bebanmaks+ "', nama_kapten = '" +namakapten+ "', asal = '" 
                +asal+ "', tujuan = '" +tujuan+ "', keberangkatan = '" +keberangkatan+ "', kedatangan = '" 
                +kedatangan+ "', kontainer = '" +container+ "', beban_bawaan = '" +bebanbarang+ "' WHERE kode_kapal = '" 
                +kodekapal+ "';";
        if(bebanbarang < bebanmaks){
            stm = con.createStatement();
            stm.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "berhasil diupdate !!,Lakukan Refresh!!");
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Beban Barang Melebihi Beban Maks!!!");
        }
        }catch(SQLException e){
            System.out.println("Method Update Error : " + e.getMessage());
        }
    }
    private void clear(){
        txtKodeKapal.setText(null);
        txtNamaKapal.setText(null);
        txtBebanMaks.setText(null);
        txtNamaKapten.setText(null);
        txtAsal.setText(null);
        txtTujuan.setText(null);
        txtKeberangkatan.setText(null);
        txtKedatangan.setText(null);
        txtContainer.setText(null);
        txtBebanBarang.setText(null);
    }
    public editdata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCariKodeKapal = new javax.swing.JTextField();
        tbCari = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtKodeKapal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNamaKapal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBebanMaks = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNamaKapten = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAsal = new javax.swing.JTextField();
        txtTujuan = new javax.swing.JTextField();
        txtKeberangkatan = new javax.swing.JTextField();
        txtKedatangan = new javax.swing.JTextField();
        txtContainer = new javax.swing.JTextField();
        txtBebanBarang = new javax.swing.JTextField();
        tbEdit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tbKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 204));
        jLabel1.setText("Edit Data");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(38, 38, 38))
        );

        txtCariKodeKapal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariKodeKapalActionPerformed(evt);
            }
        });

        tbCari.setText("Cari");
        tbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCariActionPerformed(evt);
            }
        });

        jLabel2.setText("Kode Kapal");

        jLabel3.setText("Nama Kapal");

        jLabel4.setText("Beban Maks");

        jLabel5.setText("Nama Kapten");

        jLabel6.setText("Asal");

        jLabel7.setText("Tujuan");

        jLabel8.setText("Keberangkatan");

        jLabel9.setText("Kedatangan");

        jLabel10.setText("Container");

        jLabel11.setText("Beban Barang");

        tbEdit.setText("Edit");
        tbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbEditActionPerformed(evt);
            }
        });

        jLabel12.setText("YY-MM-DD HH:MM:SS");

        jLabel13.setText("YY-MM-DD HH:MM:SS");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Input Kode Kapal :");

        tbKembali.setText("Kembali");
        tbKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaKapal)
                            .addComponent(txtBebanMaks)
                            .addComponent(txtNamaKapten)
                            .addComponent(txtAsal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTujuan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtKeberangkatan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtKedatangan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtContainer)
                            .addComponent(txtBebanBarang, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKodeKapal, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(tbEdit)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txtCariKodeKapal, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbCari)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tbKembali)
                .addGap(213, 213, 213))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCariKodeKapal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbCari)
                    .addComponent(jLabel14))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKodeKapal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaKapal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBebanMaks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNamaKapten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtKeberangkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtKedatangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtBebanBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbKembali)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariKodeKapalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariKodeKapalActionPerformed
       
    }//GEN-LAST:event_txtCariKodeKapalActionPerformed

    private void tbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCariActionPerformed
        cari();
    }//GEN-LAST:event_tbCariActionPerformed

    private void tbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbEditActionPerformed
        edit_data();
    }//GEN-LAST:event_tbEditActionPerformed

    private void tbKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKembaliActionPerformed
        this.dispose();
    }//GEN-LAST:event_tbKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editdata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tbCari;
    private javax.swing.JButton tbEdit;
    private javax.swing.JButton tbKembali;
    private javax.swing.JTextField txtAsal;
    private javax.swing.JTextField txtBebanBarang;
    private javax.swing.JTextField txtBebanMaks;
    private javax.swing.JTextField txtCariKodeKapal;
    private javax.swing.JTextField txtContainer;
    private javax.swing.JTextField txtKeberangkatan;
    private javax.swing.JTextField txtKedatangan;
    private javax.swing.JTextField txtKodeKapal;
    private javax.swing.JTextField txtNamaKapal;
    private javax.swing.JTextField txtNamaKapten;
    private javax.swing.JTextField txtTujuan;
    // End of variables declaration//GEN-END:variables
}
