package finalprojectpbo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class User extends javax.swing.JFrame {
    
    private void clear(){
        txtCari.setText(null);
    }
    String sql;
    String cari;
    
    static Connection con;
    static Statement stm;
    static ResultSet rs;
    
    private void mencari(){
        cari = txtCari.getText();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Kapal");
        model.addColumn("Nama Kapal");
        model.addColumn("Beban Maks (kg)");
        model.addColumn("Nama Kapten");
        model.addColumn("Asal");
        model.addColumn("Tujuan");
        model.addColumn("Keberangkatan");
        model.addColumn("Kedatangan");
        model.addColumn("Container");
        model.addColumn("Beban Bawaan (kg)");
        
        try{
            sql ="SELECT * FROM kapal WHERE kode_kapal LIKE '%" + cari + "%' "
                    + "OR nama_kapal LIKE '%" + cari + "%' OR Container_MAX LIKE '%" + cari +  "%' "
                    + "OR nama_kapten LIKE '%" + cari + "%' OR asal LIKE '%" + cari + "%' "
                    + "OR tujuan LIKE '%" + cari + "%' "
                    + "OR keberangkatan LIKE '%" + cari + "%' OR kedatangan LIKE '%" + cari + "%' "
                    + "OR kontainer LIKE '%" + cari + "%' OR beban_bawaan LIKE '%" + cari + "%';";
            con = (Connection) config.configDB();
            stm = con.createStatement();
            rs  = stm.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), 
                                          rs.getString(3), rs.getString(4), 
                                          rs.getString(5), rs.getString(6), 
                                          rs.getString(7), rs.getString(8),
                                          rs.getString(9), rs.getString(10)});
                                         }
            tabelKapal.setModel(model);

        }catch(SQLException e){
            System.out.println("Error = "+e.getMessage());
        }
        clear();
    }
    
    private void tampil_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Kapal");
        model.addColumn("Nama Kapal");
        model.addColumn("Beban Maks (kg)");
        model.addColumn("Nama Kapten");
        model.addColumn("Asal");
        model.addColumn("Tujuan");
        model.addColumn("Keberangkatan");
        model.addColumn("Kedatangan");
        model.addColumn("Container");
        model.addColumn("Beban Bawaan (kg)");
        
        try{
            sql ="SELECT * FROM kapal";
            con = (Connection) config.configDB();
            stm = con.createStatement();
            rs  = stm.executeQuery(sql);
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), 
                                          rs.getString(3), rs.getString(4), 
                                          rs.getString(5), rs.getString(6), 
                                          rs.getString(7), rs.getString(8),
                                          rs.getString(9), rs.getString(10)});
                                         }
            tabelKapal.setModel(model);

        }catch(SQLException e){
            System.out.println("Error = "+e.getMessage());
        }
    }
    
    public User() {
        initComponents();
        tampil_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKapal = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tbCari = new javax.swing.JButton();
        tbLogout = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelKapal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelKapal.setEnabled(false);
        jScrollPane1.setViewportView(tabelKapal);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Data Kapal");

        tbCari.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\finalprojectpbo\\src\\resource\\serach.png")); // NOI18N
        tbCari.setText("Cari");
        tbCari.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCariActionPerformed(evt);
            }
        });

        tbLogout.setText("Exit");
        tbLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(374, 374, 374)
                .addComponent(tbLogout)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbCari, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbLogout)
                    .addComponent(jLabel1))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbCari, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCariActionPerformed
        mencari();
    }//GEN-LAST:event_tbCariActionPerformed

    private void tbLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbLogoutActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Apakah anda Ingin Keluar??","Exit"
                ,JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION){
            landingpage lp = new landingpage();
            lp.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_tbLogoutActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKapal;
    private javax.swing.JButton tbCari;
    private javax.swing.JButton tbLogout;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
